(function(){
'use strict';
const $=id=>document.getElementById(id);
const state={name:'데모 데이터',master:[],content:[],edu:[],perceptionRaw:[],perception:[],sales:[],rec:[],delivery:[],impact:[],qm:[],filtered:[]};
const aliases={master:['01_안경사마스터','안경사마스터','안경사기본정보'],content:['02_교육콘텐츠','교육콘텐츠','카카오톡 콘텐츠 리스트','콘텐츠 리스트'],edu:['03_교육참여','교육참여','교육이력','수강이력'],perception:['05_인식조사','인식조사','설문'],sales:['06_피팅판매','피팅판매','판매데이터','판매 분석'],rec:['08_교육추천','교육추천결과','AI추천결과','추천결과'],delivery:['09_발송','발송시청','발송요청관리','발송결과'],impact:['10_교육효과','교육효과측정','효과측정'],qm:['인식문항마스터','문항마스터']};
const meta=['안경사ID','조사일','응답일','조사명','조사차수','안경사명','안경원명','안경원코드','지역','연차','연령대','Tier','채널','Team','담당영업사원','비고','Timestamp'];
const clean=v=>v==null?'':String(v).trim();
const k=v=>clean(v).replace(/[\s_\-()\/]/g,'').toLowerCase();
const n=v=>{if(v===''||v==null)return null; const x=Number(String(v).replace(/,/g,'').replace(/%/g,'')); return Number.isFinite(x)?x:null;};
const avg=(a,fn)=>{const v=a.map(fn).filter(x=>x!=null&&Number.isFinite(Number(x))).map(Number);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};
const yes=v=>/^(y|yes|true|1|완료|수료|시청|발송완료|성공)$/i.test(clean(v));
const pct=v=>v==null?'데이터 없음':`${Math.round(Number(v)*100)}%`;
const score=v=>v==null?'데이터 없음':`${Number(v).toFixed(1)}점`;
const esc=s=>clean(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function get(row,names){if(!row)return'';const m={};Object.keys(row).forEach(x=>m[k(x)]=row[x]);for(const name of names){const v=m[k(name)];if(v!==undefined&&clean(v)!=='')return v}return''}
function sheet(wb,names){const name=wb.SheetNames.find(s=>names.some(a=>k(s).includes(k(a))));return name?XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:true}):[]}
function latest(rows,fields){return[...rows].sort((a,b)=>{const av=fields.map(f=>clean(a[f]||get(a,[f]))).find(Boolean)||'';const bv=fields.map(f=>clean(b[f]||get(b,[f]))).find(Boolean)||'';return bv.localeCompare(av)} )[0]}
function infer(q){q=clean(q);if(/멀티포컬|MF|노안|가입도|동공|우위안/.test(q))return'멀티포컬';if(/난시|저난시|ASD|토릭/.test(q))return'난시/저난시';if(/MAX|맥스|블루/.test(q))return'MAX/블루라이트';if(/아큐브|브랜드|추천|신뢰|첫.?번째|1순위|우선/.test(q))return'브랜드/아큐브 추천';if(/피팅|검안|상담|설명|응대/.test(q))return'피팅/상담';return'기타 인식'}
function normMaster(rows){return rows.map((r,i)=>({...r,안경사ID:clean(get(r,['안경사ID','OpticianID','ID']))||`AUTO-${i+1}`,안경사명:clean(get(r,['안경사명','이름','성명'])),안경원코드:clean(get(r,['안경원코드','거래처코드'])),안경원명:clean(get(r,['안경원명','안경원','거래처명'])),지역:clean(get(r,['지역','시도'])),연차:clean(get(r,['연차','경력'])),연령대:clean(get(r,['연령대'])),Tier:clean(get(r,['Tier','티어','등급'])),채널:clean(get(r,['채널','Channel'])),Team:clean(get(r,['Team','팀'])),담당영업사원:clean(get(r,['담당영업사원','담당자','영업사원']))})).filter(r=>r.안경사ID||r.안경사명)}
function normQm(rows){return rows.map((r,i)=>({문항ID:clean(get(r,['문항ID','QuestionID']))||`Q${String(i+1).padStart(3,'0')}`,문항:clean(get(r,['문항','문항명','Question'])),인식영역:clean(get(r,['인식영역','영역']))||infer(get(r,['문항','문항명','Question'])),긍정방향:clean(get(r,['긍정방향']))||'높을수록 긍정',목표값:n(get(r,['목표값']))??4,추천교육ID:clean(get(r,['추천교육ID','교육ID'])),추천유형:clean(get(r,['추천유형'])),분석사용여부:clean(get(r,['분석사용여부','사용여부']))||'Y'})).filter(x=>x.문항ID||x.문항)}
function qm(col){const c=clean(col);const id=(c.match(/^(Q\d{2,4})[_\-\s]*/i)||[])[1];return state.qm.find(q=>k(q.문항ID)===k(id||c))||state.qm.find(q=>k(q.문항)===k(c.replace(/^Q\d{2,4}[_\-\s]*/i,'')))||state.qm.find(q=>c.includes(q.문항)||q.문항.includes(c))}
function normPerception(rows){const out=[];rows.forEach((r,ri)=>{const id=clean(get(r,['안경사ID','OpticianID','ID']));const date=clean(get(r,['조사일','응답일','Timestamp']));if(('문항'in r||'문항ID'in r)&&('응답점수'in r||'응답'in r)){const q0=clean(get(r,['문항','문항명','문항ID']));const m=qm(q0)||{};out.push({안경사ID:id,조사일:date,문항ID:get(r,['문항ID'])||m.문항ID||q0,문항:get(r,['문항','문항명'])||m.문항||q0,인식영역:get(r,['인식영역'])||m.인식영역||infer(q0),긍정방향:m.긍정방향||'높을수록 긍정',추천교육ID:m.추천교육ID||'',원점수:n(get(r,['응답점수','응답']))});return;}Object.keys(r).forEach(col=>{if(meta.some(m=>k(m)===k(col)))return;const val=n(r[col]);if(val==null)return;const m=qm(col)||{};const question=m.문항||clean(col).replace(/^Q\d{2,4}[_\-\s]*/i,'');out.push({안경사ID:id,조사일:date,문항ID:m.문항ID||(clean(col).match(/^(Q\d{2,4})/i)||[])[1]||col,문항:question,인식영역:m.인식영역||infer(question),긍정방향:m.긍정방향||'높을수록 긍정',추천교육ID:m.추천교육ID||'',원점수:val})})});return out.filter(x=>x.안경사ID&&x.문항&&x.원점수!=null)}
function pScore(x){return /낮을수록/.test(x.긍정방향)?6-Number(x.원점수):Number(x.원점수)}
function lowP(x){const s=pScore(x);return s!=null&&s<3.5}
function normRec(rows){return rows.map((r,i)=>({...r,추천ID:clean(get(r,['추천ID','ID']))||`REC-${i+1}`,안경사ID:clean(get(r,['안경사ID','OpticianID'])),추천순위:n(get(r,['추천순위','순위']))??1,교육ID:clean(get(r,['교육ID','추천교육ID'])),추천교육명:clean(get(r,['추천교육명','교육명'])),추천유형:clean(get(r,['추천유형','유형'])),추천사유요약:clean(get(r,['추천사유요약','추천사유','사유'])),근거1:clean(get(r,['근거1'])),근거2:clean(get(r,['근거2'])),근거3:clean(get(r,['근거3'])),우선순위:clean(get(r,['우선순위','Priority']))||'중간',추천상태:clean(get(r,['추천상태','상태']))})).filter(r=>r.안경사ID||r.추천교육명||r.교육ID)}
function contentName(id){const c=state.content.find(x=>clean(get(x,['교육ID','ID']))===clean(id));return clean(get(c,['교육명','콘텐츠명']))||clean(id)}
function person(id){const p=state.master.find(x=>x.안경사ID===id);const edu=state.edu.filter(x=>clean(get(x,['안경사ID']))===id);const perc=state.perception.filter(x=>x.안경사ID===id);const sales=state.sales.filter(x=>clean(get(x,['안경사ID']))===id||clean(get(x,['안경원코드']))===clean(p?.안경원코드));const rec=state.rec.filter(x=>x.안경사ID===id).sort((a,b)=>(a.추천순위||99)-(b.추천순위||99));const del=state.delivery.filter(x=>clean(get(x,['안경사ID']))===id);const imp=state.impact.filter(x=>clean(get(x,['안경사ID']))===id);const sale=latest(sales,['기준월','월','Month','날짜']);return{p,edu,perc,sales,rec,del,imp,eduRate:edu.length?edu.filter(x=>yes(get(x,['수료여부','완료여부','참여여부']))).length/edu.length:null,pAvg:avg(perc,pScore),acuvue:n(get(sale,['아큐브판매비중','아큐브비중'])),mf:n(get(sale,['아큐브멀티포컬비중','멀티포컬비중'])),ast:n(get(sale,['아큐브난시비중','난시비중'])),topRec:rec[0]}}
function badge(v){const c=v==='높음'?'high':v==='중간'?'medium':'low';return`<span class="pill ${c}">${esc(v||'낮음')}</span>`}
function kpi(label,value,note){return`<div class="kpi-card"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`}
function bar(label,v,max,suffix){let d='데이터 없음',w=0;if(v!=null){if(suffix==='%'){d=`${Math.round(v*100)}%`;w=Math.min(100,Math.max(0,v*100))}else{d=`${Number(v).toFixed(1)}${suffix}`;w=Math.min(100,Math.max(0,v/max*100))}}return`<div class="metric"><div class="metric-head"><span>${label}</span><b>${d}</b></div><div class="bar"><i style="width:${w}%"></i></div></div>`}
function filtered(){let rows=[...state.master];const m={regionFilter:'지역',yearsFilter:'연차',tierFilter:'Tier',channelFilter:'채널',repFilter:'담당영업사원'};Object.entries(m).forEach(([id,f])=>{const v=$(id)?.value;if(v)rows=rows.filter(r=>clean(r[f])===v)});const q=clean(state.query||$('smartQuery')?.value);if(q){const y=(q.match(/(\d+)\s*년차/)||[])[1];if(y)rows=rows.filter(r=>clean(r.연차).includes(y));const prod=/멀티포컬|MF/i.test(q)?'멀티포컬':/난시|저난시|ASD/i.test(q)?'난시':/MAX|맥스/i.test(q)?'MAX':'';const wantLow=/인식.*낮|인식.*필요|인식 변화/.test(q);const needEdu=/교육.*필요|추천교육/.test(q);const lowSales=/판매.*낮|판매.*오르지|미전환/.test(q);const text=q.replace(/\d+\s*년차|MAX|맥스|멀티포컬|난시|저난시|ASD|교육|필요|인식|낮은|판매|오르지|않은|중|안경사|매장/g,'').trim();if(text.length>=2)rows=rows.filter(r=>[r.안경사ID,r.안경사명,r.안경원명,r.지역,r.Tier,r.채널].join(' ').includes(text));if(prod||wantLow||needEdu||lowSales){rows=rows.filter(r=>{const m=person(r.안경사ID);const txt=[m.topRec?.추천교육명,m.topRec?.추천사유요약,...m.perc.map(x=>x.문항+' '+x.인식영역)].join(' ');if(prod&&!txt.includes(prod))return false;if(wantLow&&!m.perc.some(lowP))return false;if(needEdu&&!m.topRec)return false;if(lowSales){const base=avg(state.master,x=>person(x.안경사ID).acuvue);if(m.acuvue==null||base==null||m.acuvue>=base)return false}return true})}}return rows}
function render(){const rows=filtered();state.filtered=rows;const ids=new Set(rows.map(r=>r.안경사ID));const recs=state.rec.filter(r=>ids.has(r.안경사ID));const dels=state.delivery.filter(r=>ids.has(clean(get(r,['안경사ID']))));const imps=state.impact.filter(r=>ids.has(clean(get(r,['안경사ID']))));const first=state.perception.filter(p=>ids.has(p.안경사ID)&&/아큐브|첫.?번째|1순위|우선/.test(p.문항));$('kpiGrid').innerHTML=[kpi('전체 관리 안경사',rows.length.toLocaleString('ko-KR'),'현재 필터'),kpi('교육추천 필요',new Set(recs.map(x=>x.안경사ID)).size,'추천 결과 보유'),kpi('추천 생성',recs.length,'추천 건'),kpi('발송 완료',dels.filter(x=>/발송완료|성공/.test(clean(get(x,['발송상태','발송결과'])))).length,'발송/결과 기준'),kpi('시청/수료',dels.filter(x=>yes(get(x,['수료여부','시청여부','승인여부']))).length,'완료 기준'),kpi('아큐브 1순위 추천',avg(first,pScore)==null?'데이터 없음':pct(avg(first,pScore)/5),'문항 기반'),kpi('교육 후 판매 개선',imps.filter(x=>n(get(x,['아큐브비중변화','제품군비중변화']))>0||/개선|성장/.test(clean(get(x,['효과판정'])))).length,'효과측정')].join('');const ms=rows.map(r=>person(r.안경사ID));$('gapCards').innerHTML=[['education','교육 Gap',ms.filter(x=>x.eduRate==null||x.eduRate<1).length],['perception','인식 Gap',ms.filter(x=>x.perc.some(lowP)).length],['sales','판매 Gap',ms.filter(x=>x.acuvue!=null&&x.acuvue<(avg(ms,y=>y.acuvue)||0)).length]].map(g=>`<div class="gap-card ${g[0]}"><span>${g[1]}</span><b>${g[2]}명</b><small>현재 그룹 기준</small></div>`).join('');const top={};recs.forEach(r=>{const name=r.추천교육명||contentName(r.교육ID);if(name)top[name]=(top[name]||0)+1});$('topEducation').innerHTML=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,6).map((x,i)=>`<div class="rank-item"><span class="rank-no">${i+1}</span><b>${esc(x[0])}</b><span>${x[1]}명</span></div>`).join('')||'<div class="empty-state">추천 결과가 없습니다.</div>';$('funnel').innerHTML=[['관리대상',rows.length],['추천대상',new Set(recs.map(x=>x.안경사ID)).size],['발송완료',new Set(dels.filter(x=>/발송완료|성공/.test(clean(get(x,['발송상태','발송결과'])))).map(x=>clean(get(x,['안경사ID'])))).size],['시청/수료',new Set(dels.filter(x=>yes(get(x,['수료여부','시청여부','승인여부']))).map(x=>clean(get(x,['안경사ID'])))).size],['효과측정',new Set(imps.map(x=>clean(get(x,['안경사ID'])))).size],['판매개선',new Set(imps.filter(x=>n(get(x,['아큐브비중변화','제품군비중변화']))>0||/개선|성장/.test(clean(get(x,['효과판정'])))).map(x=>clean(get(x,['안경사ID'])))).size]].map(s=>`<div class="funnel-step"><small>${s[0]}</small><strong>${s[1]}</strong></div>`).join('');renderSegment(rows,ms);renderRec(rows);renderImpact(rows);renderQuestion(rows)}
function renderSegment(rows,ms=rows.map(r=>person(r.안경사ID))){$('segmentSummary').innerHTML=`<div class="three-col"><div>${bar('평균 인식',avg(ms,x=>x.pAvg),5,'점')}</div><div>${bar('평균 아큐브 비중',avg(ms,x=>x.acuvue),1,'%')}</div><div>${bar('평균 교육 수료율',avg(ms,x=>x.eduRate),1,'%')}</div></div>`;$('resultCount').textContent=`${rows.length}명`;$('segmentTable').innerHTML=ms.map(m=>`<tr data-id="${esc(m.p?.안경사ID)}"><td><b>${esc(m.p?.안경사명)}</b><small><br>${esc(m.p?.안경사ID)}</small></td><td>${esc(m.p?.안경원명)}<small><br>${esc(m.p?.지역)} · ${esc(m.p?.채널)}</small></td><td>${esc(m.p?.연차)} / ${esc(m.p?.Tier)}</td><td>${pct(m.eduRate)}</td><td>${score(m.pAvg)}</td><td>${pct(m.acuvue)}</td><td>${esc(m.topRec?(m.topRec.추천교육명||contentName(m.topRec.교육ID)):'없음')}</td><td>${badge(m.topRec?.우선순위)}</td></tr>`).join('');document.querySelectorAll('#segmentTable tr').forEach(tr=>tr.onclick=()=>showProfile(tr.dataset.id))}
function renderRec(rows){const ids=new Set(rows.map(x=>x.안경사ID));const recs=state.rec.filter(x=>ids.has(x.안경사ID));$('recommendationKpis').innerHTML=[kpi('추천 대상',new Set(recs.map(x=>x.안경사ID)).size,'안경사'),kpi('고우선순위',recs.filter(x=>x.우선순위==='높음').length,'추천 건'),kpi('발송 대기',recs.filter(x=>/발송대기|생성|검토/.test(clean(x.추천상태))).length,'추천상태'),kpi('근거 미완성',recs.filter(x=>![x.추천사유요약,x.근거1,x.근거2,x.근거3].some(Boolean)).length,'검토 필요')].join('');$('recommendationTable').innerHTML=recs.map(r=>{const p=state.master.find(x=>x.안경사ID===r.안경사ID)||{};const d=state.delivery.find(x=>clean(get(x,['추천ID']))===r.추천ID||(clean(get(x,['안경사ID']))===r.안경사ID&&clean(get(x,['교육ID']))===r.교육ID))||{};return`<tr data-id="${esc(r.안경사ID)}"><td><b>${esc(p.안경사명||r.안경사ID)}</b><small><br>${esc(p.안경원명)}</small></td><td>${esc(r.추천교육명||contentName(r.교육ID))}</td><td>${esc(r.추천유형)}</td><td>${esc(r.추천사유요약||[r.근거1,r.근거2,r.근거3].filter(Boolean).join(' / '))}</td><td>${badge(r.우선순위)}</td><td>${esc(r.추천상태)}</td><td>${esc(get(d,['발송상태','발송결과'])||'미발송')}</td><td>${esc(get(d,['수료여부','시청여부','승인여부'])||'-')}</td><td>${esc(get(d,['후속액션','담당영업사원후속조치','아큐비아메모'])||'-')}</td></tr>`}).join('')||'<tr><td colspan="9">추천 결과가 없습니다.</td></tr>';document.querySelectorAll('#recommendationTable tr[data-id]').forEach(tr=>tr.onclick=()=>showProfile(tr.dataset.id))}
function renderImpact(rows){const ids=new Set(rows.map(x=>x.안경사ID));const a=state.impact.filter(x=>ids.has(clean(get(x,['안경사ID']))));$('impactKpis').innerHTML=[kpi('효과 측정',a.length,'측정 건'),kpi('인식 개선',a.filter(x=>n(get(x,['인식변화']))>0||n(get(x,['사후인식점수']))>n(get(x,['사전인식점수']))).length,'건'),kpi('아큐브 판매 개선',a.filter(x=>n(get(x,['아큐브비중변화']))>0).length,'건'),kpi('제품군 판매 개선',a.filter(x=>n(get(x,['제품군비중변화']))>0||/개선|성장/.test(clean(get(x,['효과판정'])))).length,'건')].join('');$('impactBars').innerHTML=bar('평균 인식 변화',avg(a,x=>n(get(x,['인식변화']))),5,'점')+bar('평균 아큐브 비중 변화',avg(a,x=>n(get(x,['아큐브비중변화']))),1,'%')+bar('평균 제품군 비중 변화',avg(a,x=>n(get(x,['제품군비중변화']))),1,'%');const c={};a.forEach(x=>{const v=clean(get(x,['효과판정']))||'미분류';c[v]=(c[v]||0)+1});$('impactStatus').innerHTML=Object.entries(c).map((x,i)=>`<div class="rank-item"><span class="rank-no">${i+1}</span><b>${esc(x[0])}</b><span>${x[1]}건</span></div>`).join('')||'<div class="empty-state">효과 측정 데이터가 없습니다.</div>'}
function renderQuestion(rows){const ids=new Set(rows.map(x=>x.안경사ID));const data=state.perception.filter(x=>ids.has(x.안경사ID));const by={};data.forEach(x=>{(by[x.문항ID+'|'+x.문항]||=[]).push(x)});const stats=Object.entries(by).map(([k,a])=>{const parts=k.split('|');return{q:parts[1],area:a[0].인식영역,n:a.length,avg:avg(a,pScore),low:a.filter(lowP).length,edu:a[0].추천교육ID}}).sort((a,b)=>(a.avg??99)-(b.avg??99));$('questionInsight').innerHTML=stats[0]?`<div class="query-explanation"><b>가장 낮은 인식 문항:</b> ${esc(stats[0].q)} · ${score(stats[0].avg)} · 낮은 응답 ${stats[0].low}명 · 연결교육 ${esc(contentName(stats[0].edu)||stats[0].edu||'미지정')}</div>`:'<div class="empty-state">인식조사 데이터가 없습니다.</div>'}
function showProfile(id){const m=person(id);if(!m.p)return;view('profile');$('profileEmpty').hidden=true;$('profileContent').hidden=false;$('profileHero').innerHTML=`<div class="profile-title"><div><p class="eyebrow">OPTICIAN 360</p><h2>${esc(m.p.안경사명)} <small>${esc(m.p.안경사ID)}</small></h2><p>${esc(m.p.안경원명)}</p><div class="profile-meta"><span class="badge neutral">${esc(m.p.지역)}</span><span class="badge neutral">${esc(m.p.채널)}</span><span class="badge neutral">${esc(m.p.연차)}</span><span class="badge neutral">${esc(m.p.Tier)}</span><span class="badge neutral">담당 ${esc(m.p.담당영업사원)}</span></div></div><div>${badge(m.topRec?.우선순위)}</div></div>`;$('profileStatus').innerHTML=[['교육 상태',pct(m.eduRate),'수료율'],['인식 상태',score(m.pAvg),'문항 방향 보정'],['아큐브 판매',pct(m.acuvue),'최근/매핑 데이터'],['MF 비중',pct(m.mf),'최근/매핑 데이터'],['난시 비중',pct(m.ast),'최근/매핑 데이터'],['낮은 인식 문항',m.perc.filter(lowP).length+'개','변화 필요']].map(x=>`<article class="panel status-card"><h3>${x[0]}</h3><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');const lows=m.perc.filter(lowP).sort((a,b)=>pScore(a)-pScore(b)).slice(0,5);$('profileRecommendation').innerHTML=m.topRec?`<div class="recommendation-box"><h3>${esc(m.topRec.추천교육명||contentName(m.topRec.교육ID))}</h3><p>${esc(m.topRec.추천사유요약)}</p><ul>${[m.topRec.근거1,m.topRec.근거2,m.topRec.근거3].filter(Boolean).map(x=>`<li>${esc(x)}</li>`).join('')}${lows.map(x=>`<li>낮은 인식 문항: ${esc(x.문항)} (${score(pScore(x))})</li>`).join('')}</ul></div>`:`<div class="recommendation-box"><h3>추천 결과 없음</h3><ul>${lows.map(x=>`<li>${esc(x.문항)} (${score(pScore(x))}) · 연결교육 ${esc(contentName(x.추천교육ID)||x.추천교육ID||'미지정')}</li>`).join('')}</ul></div>`;const ev=[];m.edu.forEach(x=>ev.push([get(x,['교육일','완료일','신청일']),'교육',`${contentName(get(x,['교육ID']))||get(x,['교육ID'])} · ${get(x,['수료여부','참여여부'])}`]));m.perc.forEach(x=>ev.push([x.조사일,'인식조사',`${x.문항} · 원점수 ${x.원점수}`]));m.sales.forEach(x=>ev.push([get(x,['기준월','월','Month']),'판매/피팅',`아큐브 비중 ${pct(n(get(x,['아큐브판매비중','아큐브비중'])))}`]));m.del.forEach(x=>ev.push([get(x,['발송일','요청일']),'발송/시청',`${get(x,['발송상태','발송결과'])} · ${get(x,['수료여부','시청여부','승인여부'])}`]));$('profileTimeline').innerHTML=ev.filter(x=>x[0]).sort((a,b)=>clean(b[0]).localeCompare(clean(a[0]))).slice(0,20).map(x=>`<div class="timeline-item"><b>${esc(x[1])}</b><small>${esc(x[0])} · ${esc(x[2])}</small></div>`).join('')||'<p>타임라인 데이터가 없습니다.</p>'}
function view(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelector(`.tab[data-view="${id}"]`)?.classList.add('active')}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function buildFilters(){const m={regionFilter:'지역',yearsFilter:'연차',tierFilter:'Tier',channelFilter:'채널',repFilter:'담당영업사원'};Object.entries(m).forEach(([id,f])=>{const el=$(id);const cur=el.value;const vals=[...new Set(state.master.map(x=>clean(x[f])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko',{numeric:true}));el.innerHTML='<option value="">전체</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('');el.value=vals.includes(cur)?cur:'';el.onchange=()=>{state.query='';render()}})}
async function upload(file){if(!window.XLSX){toast('엑셀 라이브러리를 불러오지 못했습니다. 인터넷/CDN 접근을 확인해 주세요.');return}const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});state.name=file.name;state.master=normMaster(sheet(wb,aliases.master));state.content=sheet(wb,aliases.content);state.edu=sheet(wb,aliases.edu);state.qm=normQm(sheet(wb,aliases.qm));state.perceptionRaw=sheet(wb,aliases.perception);state.perception=normPerception(state.perceptionRaw);state.sales=sheet(wb,aliases.sales);state.rec=normRec(sheet(wb,aliases.rec));state.delivery=sheet(wb,aliases.delivery);state.impact=sheet(wb,aliases.impact);buildFilters();render();$('uploadStatus').textContent=file.name;toast(`업로드 완료: 안경사 ${state.master.length}명, 인식 응답 ${state.perception.length}건`)}
function download(){const rows=(state.filtered.length?state.filtered:filtered()).map(p=>{const m=person(p.안경사ID);return{안경사ID:p.안경사ID,안경사명:p.안경사명,안경원명:p.안경원명,지역:p.지역,연차:p.연차,Tier:p.Tier,채널:p.채널,담당영업사원:p.담당영업사원,교육수료율:m.eduRate,인식평균:m.pAvg,아큐브판매비중:m.acuvue,추천교육:m.topRec?(m.topRec.추천교육명||contentName(m.topRec.교육ID)):'',추천사유:m.topRec?.추천사유요약||'',우선순위:m.topRec?.우선순위||''}});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'검색결과');XLSX.writeFile(wb,'ACUVUE_교육추천_검색결과.xlsx')}
function seed(){state.master=normMaster([{안경사ID:'A001',안경사명:'홍길동',안경원명:'A안경원',지역:'서울',연차:'3년차',Tier:'Gold',채널:'I/O',담당영업사원:'김담당'},{안경사ID:'A002',안경사명:'김민지',안경원명:'B안경원',지역:'경기',연차:'5년차',Tier:'Silver',채널:'Top50',담당영업사원:'이담당'}]);state.content=[{교육ID:'E024',교육명:'숫자로 보는 난시'},{교육ID:'E003',교육명:'성공적인 멀티포컬 피팅'}];state.qm=normQm([{문항ID:'Q001',문항:'저난시도 교정해야 한다고 생각한다',인식영역:'난시/저난시',긍정방향:'높을수록 긍정',추천교육ID:'E024'},{문항ID:'Q002',문항:'멀티포컬 렌즈를 성공적으로 피팅할 자신이 있다',인식영역:'멀티포컬',긍정방향:'높을수록 긍정',추천교육ID:'E003'}]);state.perceptionRaw=[{안경사ID:'A001',조사일:'2026-07-01','Q001_저난시도 교정해야 한다고 생각한다':2,'Q002_멀티포컬 렌즈를 성공적으로 피팅할 자신이 있다':3},{안경사ID:'A002',조사일:'2026-07-01','Q001_저난시도 교정해야 한다고 생각한다':4,'Q002_멀티포컬 렌즈를 성공적으로 피팅할 자신이 있다':2}];state.perception=normPerception(state.perceptionRaw);state.rec=normRec([{안경사ID:'A001',추천교육명:'숫자로 보는 난시',추천사유요약:'저난시 인식 보완',우선순위:'높음'}]);buildFilters();render()}

function parseCsv(text){
 const rows=[];let row=[],cell='',q=false;
 for(let i=0;i<text.length;i++){
  const ch=text[i],nx=text[i+1];
  if(ch==='"'&&q&&nx==='"'){cell+='"';i++;continue}
  if(ch==='"'){q=!q;continue}
  if(ch===','&&!q){row.push(cell);cell='';continue}
  if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cell);if(row.some(v=>clean(v)!==''))rows.push(row);row=[];cell='';continue}
  cell+=ch;
 }
 row.push(cell);if(row.some(v=>clean(v)!==''))rows.push(row);
 if(!rows.length)return[];
 const headers=rows.shift().map(h=>clean(h));
 return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,clean(r[i])])));
}
function renderExternal(rows,source='output/Competitor_Activity.csv'){
 const box=$('externalInsight'); if(!box)return;
 if(!rows||!rows.length){box.className='empty-state';box.innerHTML='경쟁사 크롤링 CSV를 찾지 못했습니다. file://로 열면 브라우저 보안 때문에 자동 fetch가 막힐 수 있으니, CSV 업로드 버튼을 사용하거나 로컬 서버로 열어주세요.';return}
 const headers=Object.keys(rows[0]).slice(0,8);
 const dateKey=headers.find(h=>/date|일자|날짜|등록|수집/i.test(h))||headers[0];
 const titleKey=headers.find(h=>/title|제목|내용|활동|교육|제품|competitor|경쟁/i.test(h))||headers[1]||headers[0];
 const brandKey=headers.find(h=>/brand|브랜드|competitor|경쟁사|회사/i.test(h));
 const sample=rows.slice(0,80);
 const byBrand={}; if(brandKey) rows.forEach(r=>{const b=r[brandKey]||'미분류';byBrand[b]=(byBrand[b]||0)+1});
 const summary=brandKey?Object.entries(byBrand).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([b,c])=>`<span class="pill neutral">${esc(b)} ${c}건</span>`).join(' '):'';
 box.className='';
 box.innerHTML=`<div class="query-explanation"><b>${esc(source)}</b> 연결 완료 · ${rows.length}건 ${summary?'<br>'+summary:''}</div><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${sample.map(r=>`<tr>${headers.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
async function loadCompetitorCsv(){
 try{const res=await fetch('output/Competitor_Activity.csv',{cache:'no-store'}); if(!res.ok)throw new Error(String(res.status)); const text=await res.text(); renderExternal(parseCsv(text),'output/Competitor_Activity.csv');}
 catch(e){renderExternal([])}
}
async function uploadCompetitorCsv(file){if(!file)return;const text=await file.text();renderExternal(parseCsv(text),file.name);toast('경쟁사 CSV 업로드 완료')}

document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>view(t.dataset.view));$('workbookInput').onchange=e=>upload(e.target.files[0]).catch(err=>{console.error(err);toast('엑셀 업로드 오류')});$('runQuery').onclick=()=>{state.query=$('smartQuery').value;render();$('queryExplanation').textContent=`검색 조건 적용: ${state.query} / 결과 ${state.filtered.length}명`;view('segment')};$('smartQuery').onkeydown=e=>{if(e.key==='Enter')$('runQuery').click()};$('resetFilters').onclick=()=>{['regionFilter','yearsFilter','tierFilter','channelFilter','repFilter'].forEach(id=>$(id).value='');$('smartQuery').value='';state.query='';render()};$('downloadResults').onclick=download;document.querySelectorAll('.examples button').forEach(b=>b.onclick=()=>{$('smartQuery').value=b.dataset.query;state.query=b.dataset.query;render();view('segment')});if($('competitorInput'))$('competitorInput').onchange=e=>uploadCompetitorCsv(e.target.files[0]);loadCompetitorCsv();seed()})
})();
